version: '3'

services:
  # Gateway主节点
  gateway-master:
    build:
      context: ./ddbr-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KITEX_LOG_LEVEL=debug
    command: -gateway master -port 8080
    networks:
      - ddbr-network
    volumes:
      - gateway-data:/app/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 5s
      retries: 3

  # Gateway从节点
  gateway-slave:
    build:
      context: ./ddbr-gateway
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - KITEX_LOG_LEVEL=debug
    command: -gateway gateway-master:8080 -port 8080
    networks:
      - ddbr-network
    volumes:
      - gateway-slave-data:/app/data
    depends_on:
      gateway-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 5s
      retries: 3
  
  # Server节点
  ddbr-server-master:
    build:
      context: ./ddbr-server
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - KITEX_LOG_LEVEL=debug
    networks:
      - ddbr-network
    volumes:
      - server-data:/app/data
    depends_on:
      gateway-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 5s
      retries: 3
  # Server节点
  ddbr-server-slave:
    build:
      context: ./ddbr-server
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - KITEX_LOG_LEVEL=debug
    networks:
      - ddbr-network
    volumes:
      - server-data:/app/data
    depends_on:
      gateway-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  ddbr-network:
    driver: bridge

volumes:
  gateway-data:
  gateway-slave-data:
  server-data: 