version: '3'

services:
  redis:
    image: redis:7.0
    container_name: redis-single
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge 