version: '3'

services:
  # Gateway主节点
  gateway-master:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KITEX_LOG_LEVEL=debug
    command: -gateway master -port 8080
    networks:
      - ddbr-network
    volumes:
      - gateway-data:/app/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 5s
      timeout: 5s
      retries: 3

  # Gateway从节点
  gateway-slave:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - KITEX_LOG_LEVEL=debug
    command: -gateway gateway-master:8080 -port 8081
    networks:
      - ddbr-network
    volumes:
      - gateway-slave-data:/app/data
    depends_on:
      gateway-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 5s
      timeout: 5s
      retries: 3


networks:
  ddbr-network:
    driver: bridge

volumes:
  gateway-data:
  gateway-slave-data: