// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package sever

import (
	"context"
	"fmt"
	"zhamghaoran/ddbr-server/kitex_gen/ddbr/rpc/common"
)

type RequestVoteReq struct {
	Term         int64 `thrift:"term,1" json:"term"`
	CandidateId  int64 `thrift:"candidateId,2" json:"candidateId"`
	LastLogIndex int64 `thrift:"lastLogIndex,3" json:"lastLogIndex"`
	LastLogTerm  int64 `thrift:"lastLogTerm,4" json:"lastLogTerm"`
}

func NewRequestVoteReq() *RequestVoteReq {
	return &RequestVoteReq{}
}

func (p *RequestVoteReq) InitDefault() {
}

func (p *RequestVoteReq) GetTerm() (v int64) {
	return p.Term
}

func (p *RequestVoteReq) GetCandidateId() (v int64) {
	return p.CandidateId
}

func (p *RequestVoteReq) GetLastLogIndex() (v int64) {
	return p.LastLogIndex
}

func (p *RequestVoteReq) GetLastLogTerm() (v int64) {
	return p.LastLogTerm
}
func (p *RequestVoteReq) SetTerm(val int64) {
	p.Term = val
}
func (p *RequestVoteReq) SetCandidateId(val int64) {
	p.CandidateId = val
}
func (p *RequestVoteReq) SetLastLogIndex(val int64) {
	p.LastLogIndex = val
}
func (p *RequestVoteReq) SetLastLogTerm(val int64) {
	p.LastLogTerm = val
}

func (p *RequestVoteReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequestVoteReq(%+v)", *p)
}

var fieldIDToName_RequestVoteReq = map[int16]string{
	1: "term",
	2: "candidateId",
	3: "lastLogIndex",
	4: "lastLogTerm",
}

type RequestVoteResp struct {
	Term        int64          `thrift:"term,1" json:"term"`
	VoteGranted bool           `thrift:"voteGranted,2" json:"voteGranted"`
	Common      *common.Common `thrift:"common,3" json:"common"`
}

func NewRequestVoteResp() *RequestVoteResp {
	return &RequestVoteResp{}
}

func (p *RequestVoteResp) InitDefault() {
}

func (p *RequestVoteResp) GetTerm() (v int64) {
	return p.Term
}

func (p *RequestVoteResp) GetVoteGranted() (v bool) {
	return p.VoteGranted
}

var RequestVoteResp_Common_DEFAULT *common.Common

func (p *RequestVoteResp) GetCommon() (v *common.Common) {
	if !p.IsSetCommon() {
		return RequestVoteResp_Common_DEFAULT
	}
	return p.Common
}
func (p *RequestVoteResp) SetTerm(val int64) {
	p.Term = val
}
func (p *RequestVoteResp) SetVoteGranted(val bool) {
	p.VoteGranted = val
}
func (p *RequestVoteResp) SetCommon(val *common.Common) {
	p.Common = val
}

func (p *RequestVoteResp) IsSetCommon() bool {
	return p.Common != nil
}

func (p *RequestVoteResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequestVoteResp(%+v)", *p)
}

var fieldIDToName_RequestVoteResp = map[int16]string{
	1: "term",
	2: "voteGranted",
	3: "common",
}

type AppendEntriesReq struct {
	Term         int64    `thrift:"term,1" json:"term"`
	LeaderId     int64    `thrift:"leaderId,2" json:"leaderId"`
	PrevLogIndex int64    `thrift:"prevLogIndex,3" json:"prevLogIndex"`
	PrevLogTerm  int64    `thrift:"prevLogTerm,4" json:"prevLogTerm"`
	Entries      []string `thrift:"entries,5" json:"entries"`
	LeaderCommit int64    `thrift:"leaderCommit,6" json:"leaderCommit"`
}

func NewAppendEntriesReq() *AppendEntriesReq {
	return &AppendEntriesReq{}
}

func (p *AppendEntriesReq) InitDefault() {
}

func (p *AppendEntriesReq) GetTerm() (v int64) {
	return p.Term
}

func (p *AppendEntriesReq) GetLeaderId() (v int64) {
	return p.LeaderId
}

func (p *AppendEntriesReq) GetPrevLogIndex() (v int64) {
	return p.PrevLogIndex
}

func (p *AppendEntriesReq) GetPrevLogTerm() (v int64) {
	return p.PrevLogTerm
}

func (p *AppendEntriesReq) GetEntries() (v []string) {
	return p.Entries
}

func (p *AppendEntriesReq) GetLeaderCommit() (v int64) {
	return p.LeaderCommit
}
func (p *AppendEntriesReq) SetTerm(val int64) {
	p.Term = val
}
func (p *AppendEntriesReq) SetLeaderId(val int64) {
	p.LeaderId = val
}
func (p *AppendEntriesReq) SetPrevLogIndex(val int64) {
	p.PrevLogIndex = val
}
func (p *AppendEntriesReq) SetPrevLogTerm(val int64) {
	p.PrevLogTerm = val
}
func (p *AppendEntriesReq) SetEntries(val []string) {
	p.Entries = val
}
func (p *AppendEntriesReq) SetLeaderCommit(val int64) {
	p.LeaderCommit = val
}

func (p *AppendEntriesReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppendEntriesReq(%+v)", *p)
}

var fieldIDToName_AppendEntriesReq = map[int16]string{
	1: "term",
	2: "leaderId",
	3: "prevLogIndex",
	4: "prevLogTerm",
	5: "entries",
	6: "leaderCommit",
}

type AppendEntriesResp struct {
	Term    int64 `thrift:"term,1" json:"term"`
	Success bool  `thrift:"success,2" json:"success"`
}

func NewAppendEntriesResp() *AppendEntriesResp {
	return &AppendEntriesResp{}
}

func (p *AppendEntriesResp) InitDefault() {
}

func (p *AppendEntriesResp) GetTerm() (v int64) {
	return p.Term
}

func (p *AppendEntriesResp) GetSuccess() (v bool) {
	return p.Success
}
func (p *AppendEntriesResp) SetTerm(val int64) {
	p.Term = val
}
func (p *AppendEntriesResp) SetSuccess(val bool) {
	p.Success = val
}

func (p *AppendEntriesResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AppendEntriesResp(%+v)", *p)
}

var fieldIDToName_AppendEntriesResp = map[int16]string{
	1: "term",
	2: "success",
}

type HeartbeatReq struct {
}

func NewHeartbeatReq() *HeartbeatReq {
	return &HeartbeatReq{}
}

func (p *HeartbeatReq) InitDefault() {
}

func (p *HeartbeatReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HeartbeatReq(%+v)", *p)
}

var fieldIDToName_HeartbeatReq = map[int16]string{}

type Heartbeatresp struct {
	Peers  []string       `thrift:"Peers,1" json:"Peers"`
	Common *common.Common `thrift:"common,255" json:"common"`
}

func NewHeartbeatresp() *Heartbeatresp {
	return &Heartbeatresp{}
}

func (p *Heartbeatresp) InitDefault() {
}

func (p *Heartbeatresp) GetPeers() (v []string) {
	return p.Peers
}

var Heartbeatresp_Common_DEFAULT *common.Common

func (p *Heartbeatresp) GetCommon() (v *common.Common) {
	if !p.IsSetCommon() {
		return Heartbeatresp_Common_DEFAULT
	}
	return p.Common
}
func (p *Heartbeatresp) SetPeers(val []string) {
	p.Peers = val
}
func (p *Heartbeatresp) SetCommon(val *common.Common) {
	p.Common = val
}

func (p *Heartbeatresp) IsSetCommon() bool {
	return p.Common != nil
}

func (p *Heartbeatresp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Heartbeatresp(%+v)", *p)
}

var fieldIDToName_Heartbeatresp = map[int16]string{
	1:   "Peers",
	255: "common",
}

type Server interface {
	RequestVote(ctx context.Context, req *RequestVoteReq) (r *RequestVoteResp, err error)

	AppendEntries(ctx context.Context, req *AppendEntriesReq) (r *AppendEntriesResp, err error)

	HeartBeat(ctx context.Context, req *HeartbeatReq) (r *Heartbeatresp, err error)
}

type ServerRequestVoteArgs struct {
	Req *RequestVoteReq `thrift:"req,1" json:"req"`
}

func NewServerRequestVoteArgs() *ServerRequestVoteArgs {
	return &ServerRequestVoteArgs{}
}

func (p *ServerRequestVoteArgs) InitDefault() {
}

var ServerRequestVoteArgs_Req_DEFAULT *RequestVoteReq

func (p *ServerRequestVoteArgs) GetReq() (v *RequestVoteReq) {
	if !p.IsSetReq() {
		return ServerRequestVoteArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ServerRequestVoteArgs) SetReq(val *RequestVoteReq) {
	p.Req = val
}

func (p *ServerRequestVoteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ServerRequestVoteArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServerRequestVoteArgs(%+v)", *p)
}

var fieldIDToName_ServerRequestVoteArgs = map[int16]string{
	1: "req",
}

type ServerRequestVoteResult struct {
	Success *RequestVoteResp `thrift:"success,0,optional" json:"success,omitempty"`
}

func NewServerRequestVoteResult() *ServerRequestVoteResult {
	return &ServerRequestVoteResult{}
}

func (p *ServerRequestVoteResult) InitDefault() {
}

var ServerRequestVoteResult_Success_DEFAULT *RequestVoteResp

func (p *ServerRequestVoteResult) GetSuccess() (v *RequestVoteResp) {
	if !p.IsSetSuccess() {
		return ServerRequestVoteResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ServerRequestVoteResult) SetSuccess(x interface{}) {
	p.Success = x.(*RequestVoteResp)
}

func (p *ServerRequestVoteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ServerRequestVoteResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServerRequestVoteResult(%+v)", *p)
}

var fieldIDToName_ServerRequestVoteResult = map[int16]string{
	0: "success",
}

type ServerAppendEntriesArgs struct {
	Req *AppendEntriesReq `thrift:"req,1" json:"req"`
}

func NewServerAppendEntriesArgs() *ServerAppendEntriesArgs {
	return &ServerAppendEntriesArgs{}
}

func (p *ServerAppendEntriesArgs) InitDefault() {
}

var ServerAppendEntriesArgs_Req_DEFAULT *AppendEntriesReq

func (p *ServerAppendEntriesArgs) GetReq() (v *AppendEntriesReq) {
	if !p.IsSetReq() {
		return ServerAppendEntriesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ServerAppendEntriesArgs) SetReq(val *AppendEntriesReq) {
	p.Req = val
}

func (p *ServerAppendEntriesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ServerAppendEntriesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServerAppendEntriesArgs(%+v)", *p)
}

var fieldIDToName_ServerAppendEntriesArgs = map[int16]string{
	1: "req",
}

type ServerAppendEntriesResult struct {
	Success *AppendEntriesResp `thrift:"success,0,optional" json:"success,omitempty"`
}

func NewServerAppendEntriesResult() *ServerAppendEntriesResult {
	return &ServerAppendEntriesResult{}
}

func (p *ServerAppendEntriesResult) InitDefault() {
}

var ServerAppendEntriesResult_Success_DEFAULT *AppendEntriesResp

func (p *ServerAppendEntriesResult) GetSuccess() (v *AppendEntriesResp) {
	if !p.IsSetSuccess() {
		return ServerAppendEntriesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ServerAppendEntriesResult) SetSuccess(x interface{}) {
	p.Success = x.(*AppendEntriesResp)
}

func (p *ServerAppendEntriesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ServerAppendEntriesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServerAppendEntriesResult(%+v)", *p)
}

var fieldIDToName_ServerAppendEntriesResult = map[int16]string{
	0: "success",
}

type ServerHeartBeatArgs struct {
	Req *HeartbeatReq `thrift:"req,1" json:"req"`
}

func NewServerHeartBeatArgs() *ServerHeartBeatArgs {
	return &ServerHeartBeatArgs{}
}

func (p *ServerHeartBeatArgs) InitDefault() {
}

var ServerHeartBeatArgs_Req_DEFAULT *HeartbeatReq

func (p *ServerHeartBeatArgs) GetReq() (v *HeartbeatReq) {
	if !p.IsSetReq() {
		return ServerHeartBeatArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ServerHeartBeatArgs) SetReq(val *HeartbeatReq) {
	p.Req = val
}

func (p *ServerHeartBeatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ServerHeartBeatArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServerHeartBeatArgs(%+v)", *p)
}

var fieldIDToName_ServerHeartBeatArgs = map[int16]string{
	1: "req",
}

type ServerHeartBeatResult struct {
	Success *Heartbeatresp `thrift:"success,0,optional" json:"success,omitempty"`
}

func NewServerHeartBeatResult() *ServerHeartBeatResult {
	return &ServerHeartBeatResult{}
}

func (p *ServerHeartBeatResult) InitDefault() {
}

var ServerHeartBeatResult_Success_DEFAULT *Heartbeatresp

func (p *ServerHeartBeatResult) GetSuccess() (v *Heartbeatresp) {
	if !p.IsSetSuccess() {
		return ServerHeartBeatResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ServerHeartBeatResult) SetSuccess(x interface{}) {
	p.Success = x.(*Heartbeatresp)
}

func (p *ServerHeartBeatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ServerHeartBeatResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ServerHeartBeatResult(%+v)", *p)
}

var fieldIDToName_ServerHeartBeatResult = map[int16]string{
	0: "success",
}
