---
name: grpcProxy-tests
on: [push, pull_request]
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - linux-amd64-grpcproxy-integration
          - linux-amd64-grpcproxy-e2e
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - env:
          TARGET: ${{ matrix.target }}
        run: |
          set -euo pipefail

          echo "${TARGET}"
          case "${TARGET}" in
            linux-amd64-grpcproxy-integration)
              GOOS=linux GOARCH=amd64 CPU=4 make test-grpcproxy-integration
              ;;
            linux-amd64-grpcproxy-e2e)
              GOOS=linux GOARCH=amd64 CPU=4 make test-grpcproxy-e2e
              ;;
            *)
              echo "Failed to find target"
              exit 1
              ;;
          esac
