// Code generated by Kitex v0.13.1. DO NOT EDIT.

package server

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	sever "zhamghaoran/ddbr-server/kitex_gen/ddbr/rpc/sever"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"requestVote": kitex.NewMethodInfo(
		requestVoteHandler,
		newServerRequestVoteArgs,
		newServerRequestVoteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"appendEntries": kitex.NewMethodInfo(
		appendEntriesHandler,
		newServerAppendEntriesArgs,
		newServerAppendEntriesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"heartBeat": kitex.NewMethodInfo(
		heartBeatHandler,
		newServerHeartBeatArgs,
		newServerHeartBeatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"joinCluster": kitex.NewMethodInfo(
		joinClusterHandler,
		newServerJoinClusterArgs,
		newServerJoinClusterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"syncLogs": kitex.NewMethodInfo(
		syncLogsHandler,
		newServerSyncLogsArgs,
		newServerSyncLogsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"set": kitex.NewMethodInfo(
		setHandler,
		newServerSetArgs,
		newServerSetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"get": kitex.NewMethodInfo(
		getHandler,
		newServerGetArgs,
		newServerGetResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"delete": kitex.NewMethodInfo(
		deleteHandler,
		newServerDeleteArgs,
		newServerDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	serverServiceInfo                = NewServiceInfo()
	serverServiceInfoForClient       = NewServiceInfoForClient()
	serverServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return serverServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return serverServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return serverServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Server"
	handlerType := (*sever.Server)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "sever",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func requestVoteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sever.ServerRequestVoteArgs)
	realResult := result.(*sever.ServerRequestVoteResult)
	success, err := handler.(sever.Server).RequestVote(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServerRequestVoteArgs() interface{} {
	return sever.NewServerRequestVoteArgs()
}

func newServerRequestVoteResult() interface{} {
	return sever.NewServerRequestVoteResult()
}

func appendEntriesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sever.ServerAppendEntriesArgs)
	realResult := result.(*sever.ServerAppendEntriesResult)
	success, err := handler.(sever.Server).AppendEntries(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServerAppendEntriesArgs() interface{} {
	return sever.NewServerAppendEntriesArgs()
}

func newServerAppendEntriesResult() interface{} {
	return sever.NewServerAppendEntriesResult()
}

func heartBeatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sever.ServerHeartBeatArgs)
	realResult := result.(*sever.ServerHeartBeatResult)
	success, err := handler.(sever.Server).HeartBeat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServerHeartBeatArgs() interface{} {
	return sever.NewServerHeartBeatArgs()
}

func newServerHeartBeatResult() interface{} {
	return sever.NewServerHeartBeatResult()
}

func joinClusterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sever.ServerJoinClusterArgs)
	realResult := result.(*sever.ServerJoinClusterResult)
	success, err := handler.(sever.Server).JoinCluster(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServerJoinClusterArgs() interface{} {
	return sever.NewServerJoinClusterArgs()
}

func newServerJoinClusterResult() interface{} {
	return sever.NewServerJoinClusterResult()
}

func syncLogsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sever.ServerSyncLogsArgs)
	realResult := result.(*sever.ServerSyncLogsResult)
	success, err := handler.(sever.Server).SyncLogs(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServerSyncLogsArgs() interface{} {
	return sever.NewServerSyncLogsArgs()
}

func newServerSyncLogsResult() interface{} {
	return sever.NewServerSyncLogsResult()
}

func setHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sever.ServerSetArgs)
	realResult := result.(*sever.ServerSetResult)
	success, err := handler.(sever.Server).Set(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServerSetArgs() interface{} {
	return sever.NewServerSetArgs()
}

func newServerSetResult() interface{} {
	return sever.NewServerSetResult()
}

func getHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sever.ServerGetArgs)
	realResult := result.(*sever.ServerGetResult)
	success, err := handler.(sever.Server).Get(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServerGetArgs() interface{} {
	return sever.NewServerGetArgs()
}

func newServerGetResult() interface{} {
	return sever.NewServerGetResult()
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sever.ServerDeleteArgs)
	realResult := result.(*sever.ServerDeleteResult)
	success, err := handler.(sever.Server).Delete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newServerDeleteArgs() interface{} {
	return sever.NewServerDeleteArgs()
}

func newServerDeleteResult() interface{} {
	return sever.NewServerDeleteResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RequestVote(ctx context.Context, req *sever.RequestVoteReq) (r *sever.RequestVoteResp, err error) {
	var _args sever.ServerRequestVoteArgs
	_args.Req = req
	var _result sever.ServerRequestVoteResult
	if err = p.c.Call(ctx, "requestVote", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AppendEntries(ctx context.Context, req *sever.AppendEntriesReq) (r *sever.AppendEntriesResp, err error) {
	var _args sever.ServerAppendEntriesArgs
	_args.Req = req
	var _result sever.ServerAppendEntriesResult
	if err = p.c.Call(ctx, "appendEntries", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HeartBeat(ctx context.Context, req *sever.HeartbeatReq) (r *sever.Heartbeatresp, err error) {
	var _args sever.ServerHeartBeatArgs
	_args.Req = req
	var _result sever.ServerHeartBeatResult
	if err = p.c.Call(ctx, "heartBeat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) JoinCluster(ctx context.Context, req *sever.JoinClusterReq) (r *sever.JoinClusterResp, err error) {
	var _args sever.ServerJoinClusterArgs
	_args.Req = req
	var _result sever.ServerJoinClusterResult
	if err = p.c.Call(ctx, "joinCluster", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SyncLogs(ctx context.Context, req *sever.LogSyncReq) (r *sever.LogSyncResp, err error) {
	var _args sever.ServerSyncLogsArgs
	_args.Req = req
	var _result sever.ServerSyncLogsResult
	if err = p.c.Call(ctx, "syncLogs", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Set(ctx context.Context, req *sever.SetReq) (r *sever.SetResp, err error) {
	var _args sever.ServerSetArgs
	_args.Req = req
	var _result sever.ServerSetResult
	if err = p.c.Call(ctx, "set", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Get(ctx context.Context, req *sever.GetReq) (r *sever.GetResp, err error) {
	var _args sever.ServerGetArgs
	_args.Req = req
	var _result sever.ServerGetResult
	if err = p.c.Call(ctx, "get", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, req *sever.DeleteReq) (r *sever.DeleteResp, err error) {
	var _args sever.ServerDeleteArgs
	_args.Req = req
	var _result sever.ServerDeleteResult
	if err = p.c.Call(ctx, "delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
